export const projects = [
    {
        technologies: [],
        _id: "630120134042e2d798b59dc7",
        title: "Figma",
        image: "https://cdn.dribbble.com/users/3061686/screenshots/17599145/media/4d00ad57610b9f50bb00cc5a68654986.png",
        description:"Proficient in Figma for designing user interfaces and creating mockups.",
        link:"https://www.figma.com/file/Pmx0or47bgLQo13RrD7XyT/AP-Official?type=design&node-id=0%3A1&mode=design&t=E9i8Scj5vaVvmpN4-1",
    },
    {
        technologies: [],
        _id: "630120134042e2d798b59dc6",
        title: "Lorem ipsum",
        image: "https://s3-ap-south-1.amazonaws.com/static.awfis.com/wp-content/uploads/2017/07/07184649/ProjectManagement.jpg",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        link:"/",
    },
    {
        technologies: [],
        _id: "630120134042e2d798b59dc8",
        title: "Lorem ipsum",
        image: "https://s3-ap-south-1.amazonaws.com/static.awfis.com/wp-content/uploads/2017/07/07184649/ProjectManagement.jpg",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        link:"/",
    },
    {
        technologies: [],
        _id: "630120134042e2d798b59dc1",
        title: "Lorem ipsum",
        image: "https://s3-ap-south-1.amazonaws.com/static.awfis.com/wp-content/uploads/2017/07/07184649/ProjectManagement.jpg",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        link:"/",
    },
    {
        technologies: [],
        _id: "630120134042e2d798b59dc2",
        title: "Lorem ipsum",
        image: "https://s3-ap-south-1.amazonaws.com/static.awfis.com/wp-content/uploads/2017/07/07184649/ProjectManagement.jpg",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        link:"/",
    },
    {
        technologies: [],
        _id: "630120134042e2d798b59dc3",
        title: "Lorem ipsum",
        image: "https://s3-ap-south-1.amazonaws.com/static.awfis.com/wp-content/uploads/2017/07/07184649/ProjectManagement.jpg",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        link:"/",
    },
]